# Generated by Django 4.1.4 on 2022-12-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=1024)),
                ('first_name', models.CharField(max_length=1024, null=True)),
                ('last_name', models.CharField(max_length=1024, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('about_me', models.TextField(null=True)),
                ('gender', models.IntegerField(null=True)),
                ('membership_date', models.DateTimeField(null=True)),
                ('user_status', models.IntegerField(null=True)),
                ('join_date', models.DateTimeField(null=True)),
                ('last_activity', models.DateTimeField(null=True)),
                ('last_edit', models.DateTimeField(null=True)),
                ('avatar_url', models.CharField(max_length=1024, null=True)),
                ('approved_profile', models.IntegerField(null=True)),
                ('account_status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(null=True)),
                ('permissions', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('enable', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField()),
                ('reactor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactor', to='tinder.members')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tinder.members')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder.memberships'),
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_1', to='tinder.members')),
                ('user_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_2', to='tinder.members')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reactions',
            constraint=models.UniqueConstraint(fields=('reactor_id', 'receiver_id'), name='unique_reactorid_receiverid_combination'),
        ),
        migrations.AddConstraint(
            model_name='connections',
            constraint=models.UniqueConstraint(fields=('user_id_1', 'user_id_2'), name='unique_userid1_userid2_combination'),
        ),
    ]
