version: '3'
services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
      - ./data/:/usr/src/data/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev-remote
    networks:
      - tinder-group5
  
  # postgres:
  #   container_name: postgres_container
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: tinder-db
  #     PGDATA: /data/postgres
  #   volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 5s
  #     retries: 5
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - tinder-group5
  #   restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_data:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - tinder-group5
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  tinder-group5:
    name: tinder-group5