version: '3'
services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
      - ./data/:/usr/src/data/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev-remote
    networks:
      - tinder-group5
  

  # vue:
  #   build: ./wanna-date-web    
  #   volumes:
  #     - ./wanna-date-web/:/usr/src/frontend-app/
  #     - ./data/:/usr/src/data/
  #   depends_on:
  #     - web
  #   ports:
  #     - 5173:5173

  #   env_file:
  #     - ./.env.dev-remote
  #   networks:
  #     - tinder-group5


  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx/Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - vue
  #     - web
  # postgres:
  #   container_name: postgres_container
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: tinder-db
  #     PGDATA: /data/postgres
  #   volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 5s
  #     retries: 5
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - tinder-group5
  #   restart: unless-stopped
  
  #   pgadmin:
  #     container_name: pgadmin_container
  #     image: dpage/pgadmin4
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #       PGADMIN_CONFIG_SERVER_MODE: 'False'
  #     volumes:
  #        - pgadmin_data:/var/lib/pgadmin

  #     ports:
  #       - "${PGADMIN_PORT:-5050}:80"
  #     networks:
  #       - tinder-group5
  #     restart: unless-stopped

  stripe-cli:
      image: stripe/stripe-cli
      container_name: stripe-cli
      command: listen --forward-to "localhost:8000/api/profile/webhook"
      environment:
        - STRIPE_API_KEY=sk_test_51ME8c4CPnC0jXuRWQSNAY97FpbvuTuX4QU9B95NoRv8u8NDnXacgkAfPxMV0ixsgLII9tffKnRH7VrLqLHdsYacM00ywSZzHOd
        - STRIPE_DEVICE_NAME=WannaDate
      network_mode: host
volumes:
  postgres_data:
  pgadmin_data:

networks:
  tinder-group5:
    name: tinder-group5
