# Generated by Django 4.1.4 on 2022-12-11 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('is_premium', models.BooleanField(blank=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_reported', models.BooleanField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('big_picture_url', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('small_picture_url', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('country', models.CharField(blank=True, max_length=1024, null=True)),
                ('city', models.CharField(blank=True, max_length=1024, null=True)),
                ('district', models.CharField(blank=True, max_length=1024, null=True)),
                ('street', models.CharField(blank=True, max_length=1024, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('school', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
