# Generated by Django 4.1.4 on 2022-12-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_rename_user_id_membersinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='membersimages',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='memberssettings',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='members',
            name='last_name',
        ),
    ]
