# Generated by Django 4.1.4 on 2022-12-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_rename_first_name_members_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
