# Generated by Django 4.1.4 on 2022-12-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_alter_members_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='members',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='members',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='members',
            name='gender',
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='gender',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
