# Generated by Django 4.1.4 on 2022-12-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0006_remove_members_about_me_remove_members_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersimages',
            name='uploaded_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membersimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.members'),
        ),
    ]
