# Generated by Django 4.1.4 on 2022-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_remove_membersinfo_id_remove_memberssettings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
