# Generated by Django 4.0.5 on 2022-12-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0009_alter_members_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(blank=True, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='membership_date',
            field=models.DateTimeField(default='0/0/0'),
        ),
    ]
