# Generated by Django 4.0.5 on 2022-12-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0010_alter_members_email_alter_members_membership_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='membership_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
